server:
  port: 9290

# ?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: u22373138
    password: Aa861246
    url: jdbc:mysql://120.46.3.97:3306/h_db22373138?useSSL=false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

# ??mybatis???xml??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.vitalis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# ??
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

ip: localhost